### ISSUE TITLE
How to pass `named` transformation for generating image url

### ISSUE THREAD

**Issue by pratik149** [imagekit-developer/imagekit-php#18]
In the documentation, we can pass transformation as key, value pair, which looks something like this.

```
$imageURL = $imageKit->url(array(
    "path" => "/default-image.jpg",
    "transformation" => array(
        array(
            "height" => "300",
            "width" => "400",
        )
    )
));
```

But what if I want to pass a named transformation which I have configured in the imagekit dashboard? Something like below is what I'm expecting.

```
$imageURL = $imageKit->url(array(
    "path" => "/default-image.jpg",
    "transformation" => "doctors_profile" // here `doctor_profile` is the name of transformation.
));
```

May I know how can I achieve the above using this SDK?

**Comment by reganjohnson** [comment]
Hi @pratik149,

It's in their docs under the approved transformations. You would simply use...

```
$imageURL = $imageKit->url([
    'path' => '/default-image.jpg',
    'transformation' => [
        [
            'named' => 'doctors_profile',
        ],
    ],
]);
```

Hope this helps!

**Comment by pratik149** [comment]
Oh yes, thank you so much for pointing it out for me. I completely missed that bit from the documentation. TBH I just skimmed-through that list of transformations, assuming I won't find anything related to named transformation, but thanks to you for helping me out! 😄
