### ISSUE TITLE
InvalidArgumentException: Status code must be an integer value between 1xx and 5xx. in file Laravel

### ISSUE THREAD

**Issue by gerikurniawan** [imagekit-developer/imagekit-php#20]
Something happen when i use imagekit.io on laravel, anyone can helpme?

**Comment by imagekitio** [comment]
This looks more related to the underlying API response. Can you share the minimum steps to reproduce this error?

**Comment by gerikurniawan** [comment]
![ssin](https://user-images.githubusercontent.com/71430807/93496939-0aa18b80-f93a-11ea-9cbc-beba4b922b98.PNG)

and the full error :
<!--
InvalidArgumentException: Status code must be an integer value between 1xx and 5xx. in file C:\wamp64\www\backendkompetisi\vendor\guzzlehttp\psr7\src\Response.php on line 151

#0 C:\wamp64\www\backendkompetisi\vendor\guzzlehttp\psr7\src\Response.php(98): GuzzleHttp\Psr7\Response-&gt;assertStatusCodeRange(0)
#1 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Resource\GuzzleHttpWrapper.php(178): GuzzleHttp\Psr7\Response-&gt;__construct(0, Array, '')
#2 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Resource\GuzzleHttpWrapper.php(89): ImageKit\Resource\GuzzleHttpWrapper-&gt;handleRequestException(Object(GuzzleHttp\Exception\RequestException))
#3 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Upload\Upload.php(31): ImageKit\Resource\GuzzleHttpWrapper-&gt;postMultipart()
#4 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\ImageKit.php(123): ImageKit\Upload\Upload-&gt;uploadFileRequest(Array, Object(ImageKit\Resource\GuzzleHttpWrapper))
#5 C:\wamp64\www\backendkompetisi\app\Http\Controllers\MasterProductController.php(54): ImageKit\ImageKit-&gt;uploadFiles(Array)
#6 [internal function]: App\Http\Controllers\MasterProductController-&gt;store(Object(Illuminate\Http\Request))
#7 C:\wamp64\www\backendkompetisi\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#8 C:\wamp64\www\backendkompetisi\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction('store', Array)

**Comment by stivemark** [comment]
<!--
InvalidArgumentException: Status code must be an integer value between 1xx and 5xx. in file C:\wamp64\www\backendkompetisi\vendor\guzzlehttp\psr7\src\Response.php on line 151

#0 C:\wamp64\www\backendkompetisi\vendor\guzzlehttp\psr7\src\Response.php(98): GuzzleHttp\Psr7\Response-&gt;assertStatusCodeRange(0)
#1 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Resource\GuzzleHttpWrapper.php(178): GuzzleHttp\Psr7\Response-&gt;__construct(0, Array, '')
#2 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Resource\GuzzleHttpWrapper.php(89): ImageKit\Resource\GuzzleHttpWrapper-&gt;handleRequestException(Object(GuzzleHttp\Exception\RequestException))
#3 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Upload\Upload.php(31): ImageKit\Resource\GuzzleHttpWrapper-&gt;postMultipart()
#4 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\ImageKit.php(123): ImageKit\Upload\Upload-&gt;uploadFileRequest(Array, Object(ImageKit\Resource\GuzzleHttpWrapper))
#5 C:\wamp64\www\backendkompetisi\app\Http\Controllers\MasterProductController.php(54): ImageKit\ImageKit-&gt;uploadFiles(Array)
#6 [internal function]: App\Http\Controllers\MasterProductController-&gt;store(Object(Illuminate\Http\Request))
#7 C:\wamp64\www\backendkompetisi\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#8 C:\wamp64\www\backendkompetisi\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction('store', Array)

**Comment by gerikurniawan** [comment]
InvalidArgumentException: Status code must be an integer value between 1xx and 5xx. in file C:\wamp64\www\backendkompetisi\vendor\guzzlehttp\psr7\src\Response.php on line 151

#0 C:\wamp64\www\backendkompetisi\vendor\guzzlehttp\psr7\src\Response.php(98): GuzzleHttp\Psr7\Response-&gt;assertStatusCodeRange(0)
#1 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Resource\GuzzleHttpWrapper.php(178): GuzzleHttp\Psr7\Response-&gt;__construct(0, Array, '')
#2 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Resource\GuzzleHttpWrapper.php(89): ImageKit\Resource\GuzzleHttpWrapper-&gt;handleRequestException(Object(GuzzleHttp\Exception\RequestException))
#3 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\Upload\Upload.php(31): ImageKit\Resource\GuzzleHttpWrapper-&gt;postMultipart()
#4 C:\wamp64\www\backendkompetisi\vendor\imagekit\imagekit\src\ImageKit\ImageKit.php(123): ImageKit\Upload\Upload-&gt;uploadFileRequest(Array, Object(ImageKit\Resource\GuzzleHttpWrapper))
#5 C:\wamp64\www\backendkompetisi\app\Http\Controllers\MasterProductController.php(54): ImageKit\ImageKit-&gt;uploadFiles(Array)
#6 [internal function]: App\Http\Controllers\MasterProductController-&gt;store(Object(Illuminate\Http\Request))
#7 C:\wamp64\www\backendkompetisi\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#8 C:\wamp64\www\backendkompetisi\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction('store', Array)

**Comment by putera** [comment]
I got the same error here. But i am not using Laravel. just basic stuff and yet still got error.. please help.

![Error code](https://i.ibb.co/DGxVkRX/a.jpg)

Fatal error: Uncaught InvalidArgumentException: Status code must be an integer value between 1xx and 5xx.

...\public\vendor\guzzlehttp\psr7\src\Response.php on line 151

**Comment by gerikurniawan** [comment]
> This looks more related to the underlying API response. Can you share the minimum steps to reproduce this error?

is there something wrong with my code?

**Comment by VconexID** [comment]
hello @gerikurniawan do you find any solution?

**Comment by hasan-almujtaba** [comment]
also happen to me, using laravel 8.

**Comment by gausoft** [comment]
It's may related to Guzzle version, you can apply a patch in composer.json as mentioned [here](https://github.com/spatie/crawler/issues/271#issuecomment-642645685)
