### ISSUE TITLE
Solution for using Guzzle 7

### ISSUE THREAD

**Issue by putera** [imagekit-developer/imagekit-php#22]
Hi there,
Is there any solution to use this API because i am using Guzzle 7. Thanks in advance.

**Comment by imagekitio** [comment]
@putera Please share the minimum code sample and environment details to reproduce the problem you are facing with Guzzle 7.

**Comment by putera** [comment]
> @putera Please share the minimum code sample and environment details to reproduce the problem you are facing with Guzzle 7.

I already using the Guzzle 7.1 in my project. So, when i require the imagekit package via composer it will not install. See image below. What is the solution ? thanks.

![Screen Shot 2020-11-23 at 9 06 31 AM](https://user-images.githubusercontent.com/314314/99922448-946f3a00-2d6b-11eb-86e8-773bf57d3372.png)

**Comment by willyw2k** [comment]
up, in laravel 8 is using guzzle 7. im also need this packages for my project

**Comment by suresh-ramani** [comment]
> > @putera Please share the minimum code sample and environment details to reproduce the problem you are facing with Guzzle 7.
> 
> I already using the Guzzle 7.1 in my project. So, when i require the imagekit package via composer it will not install. See image below. What is the solution ? thanks.
> 
> ![Screen Shot 2020-11-23 at 9 06 31 AM](https://user-images.githubusercontent.com/314314/99922448-946f3a00-2d6b-11eb-86e8-773bf57d3372.png)

Same Error.

I sent a mail to the team but no response. :(

**Comment by imagekitio** [comment]
@putera Fixed in version 1.2.2
