### ISSUE TITLE
Folder delete function [enhancement]  

### ISSUE THREAD

**Issue by 9paradox** [imagekit-developer/imagekit-php#30]
Hi, it would be great to have a folder delete function

```php
$this->imageKit->deleteFolder($folderPath);
````

As this feature is already available via the [REST api](https://docs.imagekit.io/api-reference/media-api/delete-folder) 

_Thanks, great product!_

**Comment by imagekitio** [comment]
@9paradox Thanks for the feedback. We are planning this update for September.

**Comment by ahnv** [comment]
@9paradox `deleteFolder` function is now available in Version 2.0.0
