### ISSUE TITLE
Seo-friendly URL doesn't work with Signed URL when using transformations

### ISSUE THREAD

**Issue by fMads** [imagekit-developer/imagekit-php#34]
When using Signed URLs, there is no way of also using Seo-friendly naming when using transformations.
The is two options for adding "ik-seo" to _ImageKit\ImageKit_
1. Append it to _urlEndpoint_
```
<?php
$imageKit = new ImageKit(
    $publicKey,
    $privateKey,
    'https://ik.imagekit.io/demo/ik-seo'
);
```
2. Prepend it to _path_
```
<?php
$imageKit = new ImageKit(
    $publicKey,
    $privateKey,
    'https://ik.imagekit.io/demo'
);
$imageKit->url([
    'path' => '/ik-seo/default-image/seo-friendly-name.jpg'
);
```

Neither of the options is working.

The issue with adding to _urlEndpoint_ is, that _/ik-seo_ is then used when calculating the signature - and it should not be part of that.
And the issue with adding to _path_ is, that _/ik-seo_ is added **after** the transformations, but it should be before: `https://ik.imagekit.io/demo/tr:h-300,w-400/ik-seo/default-image/seo-friendly-name.jpg?ik-t=1634107655&ik-s=6af8d13728aae425bf63894a1040271fb2bb228c&ik-sdk-version=php-2.0.0`

So there is no way of adding seo-friendly names when both using signed URL and transformations

**Comment by imagekitio** [comment]
Please try with `'transformationPosition' => 'query'`
