### ISSUE TITLE
Origin image paths have query parameters

### ISSUE THREAD

**Issue by erikverheij** [imagekit-developer/imagekit-php#47]
Hello, we're having a situation where our origin image paths contain query parameters.

Example path: `Art_Object_Public/62113000074175459/Main_Image/image-download/4gJsEaRAh9Fv5MyFKrjj61gY6ArujW8u1HMv2pEBeKEbGuWVze6CNWwsQhpKm3ZCRU9dtgd7bjUJTG6G845GfEMVSKEbrvq1hhha/1580100858796_4013071.jpg?someParam=someValue`

The resulting url by the PHP SDK now looks like this: `https://z-art-img.kunst.nl/Art_Object_Public/62113000074175459/Main_Image/image-download/4gJsEaRAh9Fv5MyFKrjj61gY6ArujW8u1HMv2pEBeKEbGuWVze6CNWwsQhpKm3ZCRU9dtgd7bjUJTG6G845GfEMVSKEbrvq1hhha/1580100858796_4013071.jpg?someParam=someValue?ik-sdk-version=php-1.2.2`

There are 2 question marks in the url now. How could we overcome this issue?

**Comment by imagekitio** [comment]
`path` cannot contain query parameters. If that is the case, you can construct the URL in your application and use `src` parameter.

Example is here - https://github.com/imagekit-developer/imagekit-php#using-full-image-url

**Comment by erikverheij** [comment]
Thanks, we'll switch to the `src` param!
