### ISSUE TITLE
Error time expire

### ISSUE THREAD

**Issue by luizsonego** [imagekit-developer/imagekit-php#53]
Good afternoon, I'm using the image kit for a while but recently I get the error of "Your request contains invalid expire parameter. Expire parameter should be a Unix time in less than 1 hour into the future.". I've searched in various ways but without success to get around this error. It is some paramentro used by imagekit that generates this error

**Comment by imagekitio** [comment]
Which version are you using? Can you please validate on the latest 3.0.2 version? https://packagist.org/packages/imagekit/imagekit#3.0.2

**Comment by luizsonego** [comment]
yes, I'm using the latest version, but I saw the problem happens apparently because of docker, after a while running for reasons I haven't figured out yet it loses the timestamp relationship that causes this error to occur, in production this error has not happened so far
