### ISSUE TITLE
Version 3.0.1 is not released

### ISSUE THREAD

**Issue by wujekbogdan** [imagekit-developer/imagekit-php#55]
The most recent version of the `imagekit/imagekit` package at [packagist.org](https://packagist.org/packages/imagekit/imagekit) is v.3.0.0 while the most recent version of the library on Github is v.3.0.1.

**Comment by imagekitio** [comment]
Thanks for pointing out. https://packagist.org/packages/imagekit/imagekit#3.0.2 is released now.
