### ISSUE TITLE
PHP 5.6 not supported as docs indicate

### ISSUE THREAD

**Issue by flxmrk** [imagekit-developer/imagekit-php#57]
Due to `beberlei/assert`
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - beberlei/assert[v3.3.0, ..., v3.3.2] require php ^7.0 || ^8.0 -> your php version (5.6.40) does not satisfy that requirement.
    - imagekit/imagekit[3.0.0, ..., 3.0.3] require beberlei/assert ^3.3 -> satisfiable by beberlei/assert[v3.3.0, v3.3.1, v3.3.2].
    - Root composer.json requires imagekit/imagekit ^3.0 -> satisfiable by imagekit/imagekit[3.0.0, 3.0.2, 3.0.3].

**Comment by imagekitio** [comment]
@fmp777 This is fixed in version 4.0.1
