### ISSUE TITLE
Errors in sample code 

### ISSUE THREAD

**Issue by AssaultKoder95** [imagekit-developer/imagekit-php#6]
I was trying your SDK and found a few bugs in the sample code.

1. In Chained transformations as query parameters example, the second transformation contains `rotation: 90` which I believe should be `rotation => 90`

2. In Chained transformations as query parameters example, transformationPosition should be in quotes.

3. While implementing, Chained transformations as query parameters example, when I tried using transformation `lossless => false`, it resulted in **https://ik.imagekit.io/lemonbouy/tr:rt-90,lo-/default-image_Xz-dgYpaS.jpg?sdk-version=php-1.1.0** , you can see that value of the lossless parameter is empty `lo-` which should be `lo-false` and the URL should be **https://ik.imagekit.io/lemonbouy/tr:rt-90,lo-false/default-image_Xz-dgYpaS.jpg?sdk-version=php-1.1.0**

**Comment by kishanshettyb** [comment]
Thanks @AssaultKoder95 for reporting the bugs.

> In Chained transformations as query parameters example, the second transformation contains rotation: 90 which I believe should be rotation => 90

Can you point me to the code where this is present?

> In Chained transformations as query parameters example, transformationPosition should be in quotes

Can you clarify this once?

**Comment by AssaultKoder95** [comment]
Both can be found under this [link](https://github.com/imagekit-developer/imagekit-php#examples-of-generating-urls)

The key in the key-value pair should have double quotes, which is missing.
Adding a screenshot for the same.

![Screenshot 2020-02-04 at 3 04 17 PM](https://user-images.githubusercontent.com/6575313/73732172-be655a80-475f-11ea-8fe1-51bed076fe10.png)

**Comment by MrDHat** [comment]
Fixed in #9
